import { NextRequest } from 'next/server';
import { TEMPLATES, getTemplate } from '@/data/templates';

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const templateName = searchParams.get('name');

    // If requesting a specific template
    if (templateName) {
      const template = getTemplate(templateName);
      if (!template) {
        return Response.json({ error: 'Template not found' }, { status: 404 });
      }

      console.log(`📋 Serving embedded template: ${template.name}`);
      
      // For now, no cached verse detection - we'll generate it on demand
      // This can be added back later when we implement caching strategy
      
      return Response.json({
        template: {
          name: template.name,
          displayName: template.displayName,
          description: template.description
        },
        ustxData: template.ustxData,
        cachedVerseDetection: null // Will be generated by Modal/frontend
      });
    }

    // Return list of available templates
    return Response.json({
      templates: TEMPLATES.map(template => ({
        name: template.name,
        displayName: template.displayName,
        description: template.description
      }))
    });

  } catch (error) {
    console.error('Template API error:', error);
    return Response.json({ 
      error: 'Failed to load templates',
      details: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 });
  }
}

export const maxDuration = 30;